package be.stehey.foxy.backtester;

import be.stehey.foxy.backtester.model.Event;

public abstract class ExecutionHandler {
	// The ExecutionHandler abstract class handles the interaction
	// between a set of orders generated by a Portfolio and
	// the ultimate set of Fill objects that actually occur in the
	// market.
	
	// The handlers can be used to subclass simulated brokerages
	// or live brokerages, with identical interfaces. This allows
	// strategies to be backtested in a very similar manner to the
	// live trading engine.
	
	protected MessageBus messageBus;

	public abstract void executeOrder(Event event);
	// Takes an Order event and executes it, producing
	// a Fill event that gets placed onto the Events queue.
	
	// parameters:
	// event - Contains an Event object with order information.
	
}
